### ISSUE TITLE
incorrect grouping of nodes names 

### ISSUE THREAD

**Issue by KKulishov** [coroot/coroot#145]
There was a problem on one of the clusters. this is what it looks like :
![node-group](https://github.com/coroot/coroot/assets/21700458/dd992ce4-ffe8-4866-b9dc-318195d71a9c)

but metrics are present for all nodes

![node-metrics](https://github.com/coroot/coroot/assets/21700458/21bbb468-0a00-4e76-90c1-4f72489cfe19)

version kuber 1.20.12 
I use victoriametrics , but I have the same thing on other clusters victoriametrics and everything is fine. 

current problem with one of the clusters. 

Can you tell me which way to look? How coroot determines the name of the node.

**Comment by KKulishov** [comment]
It seems I found the reason. The machine ids are the same, rather the VM was copied, but the machine id was not replaced.

can you tell me if you group by node_agent_info metrics?

or I'm wrong ?

**Comment by KKulishov** [comment]
It turns out that you don’t look at the machine_id itself, but at /sys/class/dmi/id/product_uuid

here are my metrics 
![machine-id-coroot](https://github.com/coroot/coroot/assets/21700458/e92c87fb-4042-4d51-ac91-9315c1bc4de1)

if you look at the VMs themselves , product_uuid :
`
cat /sys/class/dmi/id/product_uuid
064e0f42-23ce-3200-09da-dab173b5dd77
`

**Comment by def** [comment]
The agent attempts to read the `machine_id` from the following locations in the specified order:
* /sys/devices/virtual/dmi/id/product_uuid
* /etc/machine-id
* /var/lib/dbus/machine-id

It also assumes that this `machine_id` corresponds to the `system-uuid` provided by Kubernetes. You can check the `system_uuid` label of the`kube_node_info` metric exported by kube-state-metrics.

**Comment by KKulishov** [comment]
Thank you! The problem is more likely on the hypervisor side. Since the system_uuid on 6 nodes are the same, those are the ones that are not grouped correctly.

**Comment by magberg** [comment]
Hello
We use a cloud provider, the infrastructure is on Vmware through vDirector
If the hoster did not take care in advance (https://knowledge.broadcom.com/external/article?legacyId=2002506), then all already created VMs will have the same uuid
Which is very bad. 
We saw this ourselves....

This became clearly noticeable when we started installing coroot-node-agents on virtual machines with separate application instances, for good detail service maps.

my suggestion is to change -
change the order of checking the machine_id location
With 
- /sys/devices/virtual/dmi/id/product_uuid
- /etc/machine-id
- /var/lib/dbus/machine-id

to
- /etc/machine-id
- /var/lib/dbus/machine-id
- /sys/devices/virtual/dmi/id/product_uuid

because the parameters in (/etc/machine-id / /var/lib/dbus/machine-id) can be changed in the virtual machine quite easily.
