### ISSUE TITLE
PostgreSQL Support - CloudNativePG(PostgreSQL Operator for Kubernetes)

### ISSUE THREAD

**Issue by zohebshaik41** [coroot/coroot#155]
Hi Team,

Are there any plans of supporting PostgreSQL? I know that MongoDB support is available.

In case if it can be done in future or any plans, it would be of great help.

As PostgreSQL is widely used and CloudNativePG(PostgreSQL Operator for Kubernetes) is really awesome.

**Comment by def** [comment]
Coroot already supports Postgres. Check out the relevant posts on our blog:

 * [Advanced Postgres monitoring with Coroot](https://coroot.com/blog/advanced-postgres-monitoring)
 * [Chaos testing Kubernetes Operators for Postgres: StackGres](https://coroot.com/blog/stackgres)

However, running Coroot's [pg-agent](https://github.com/coroot/coroot-pg-agent) as side-cars for of CloudNativePG instances faces challenges due to CloudNativePG's limitations.

**Comment by zohebshaik41** [comment]
Thanks for your response and update. In this case, better we will wait.
